DROP TABLE IF EXISTS user;
CREATE TABLE user (
  id          INTEGER PRIMARY KEY  AUTOINCREMENT,
  email       VARCHAR(20) NOT NULL,
  password    VARCHAR(20) NOT NULL,
  nickname    VARCHAR(20) NOT NULL,
  birthday    DATE,
  create_time DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_ip     VARCHAR(15)
);

DROP TABLE IF EXISTS user_oauth;
CREATE TABLE user_oauth (
  id          INTEGER PRIMARY KEY  AUTOINCREMENT,
  user_id     INTEGER,
  open_plat   VARCHAR(20),
  open_id     VARCHAR(20),
  access_token    VARCHAR(20) NOT NULL
);

DROP TABLE IF EXISTS author;
CREATE TABLE author (
  id    INTEGER PRIMARY KEY AUTOINCREMENT,
  name  VARCHAR(20) NOT NULL,
  email VARCHAR(20) NOT NULL
);

DROP TABLE IF EXISTS blog;
CREATE TABLE blog (
  id        INTEGER PRIMARY KEY  AUTOINCREMENT,
  author    VARCHAR(20) NOT NULL,
  title     VARCHAR(40) NOT NULL,
  pub_date  DATE,
  add_time  DATETIME             DEFAULT CURRENT_TIMESTAMP,
  edit_time DATETIME             DEFAULT CURRENT_TIMESTAMP
);
